print "The starcheat formula has been moved to it`s own tap with support for brew update and a fixed .app creation. To install type:\n"
print "  brew remove starcheat\n"
print "  brew tap chrmoritz/starcheat\n"
print "  brew install starcheat\n"
print "  brew linkapps starcheat\n"
print "From now on the starcheat formula will be updated with every brew updated and if a new version is available it will be listed in the updated formula section of brew update and in brew outdated. To update just type:\n"
print "  brew update\n"
print "  brew upgrade starcheat\n"