# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainWindow.ui'
#
# Created: Thu Dec 19 00:59:00 2013
#      by: PyQt5 UI code generator 5.1.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 575)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stats_group = QtWidgets.QGroupBox(self.centralwidget)
        self.stats_group.setGeometry(QtCore.QRect(10, 150, 281, 381))
        self.stats_group.setObjectName("stats_group")
        self.widget = QtWidgets.QWidget(self.stats_group)
        self.widget.setGeometry(QtCore.QRect(10, 20, 261, 360))
        self.widget.setObjectName("widget")
        self.stats_group_2 = QtWidgets.QFormLayout(self.widget)
        self.stats_group_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.stats_group_2.setContentsMargins(0, 0, 0, 0)
        self.stats_group_2.setObjectName("stats_group_2")
        self.health_label = QtWidgets.QLabel(self.widget)
        self.health_label.setObjectName("health_label")
        self.stats_group_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.health_label)
        self.health = QtWidgets.QSlider(self.widget)
        self.health.setMinimum(1)
        self.health.setOrientation(QtCore.Qt.Horizontal)
        self.health.setObjectName("health")
        self.stats_group_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.health)
        self.max_health_label = QtWidgets.QLabel(self.widget)
        self.max_health_label.setObjectName("max_health_label")
        self.stats_group_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.max_health_label)
        self.max_health = QtWidgets.QSpinBox(self.widget)
        self.max_health.setMinimum(1)
        self.max_health.setMaximum(1000000)
        self.max_health.setSingleStep(10)
        self.max_health.setObjectName("max_health")
        self.stats_group_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_health)
        self.invulnerable = QtWidgets.QCheckBox(self.widget)
        self.invulnerable.setObjectName("invulnerable")
        self.stats_group_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.invulnerable)
        self.godmode = QtWidgets.QCheckBox(self.widget)
        self.godmode.setObjectName("godmode")
        self.stats_group_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.godmode)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stats_group_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line)
        self.energy_label = QtWidgets.QLabel(self.widget)
        self.energy_label.setObjectName("energy_label")
        self.stats_group_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.energy_label)
        self.energy = QtWidgets.QSlider(self.widget)
        self.energy.setMinimum(1)
        self.energy.setOrientation(QtCore.Qt.Horizontal)
        self.energy.setObjectName("energy")
        self.stats_group_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.energy)
        self.max_energy_label = QtWidgets.QLabel(self.widget)
        self.max_energy_label.setObjectName("max_energy_label")
        self.stats_group_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.max_energy_label)
        self.max_energy = QtWidgets.QSpinBox(self.widget)
        self.max_energy.setMinimum(1)
        self.max_energy.setMaximum(1000000)
        self.max_energy.setSingleStep(10)
        self.max_energy.setObjectName("max_energy")
        self.stats_group_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.max_energy)
        self.energy_regen_label = QtWidgets.QLabel(self.widget)
        self.energy_regen_label.setObjectName("energy_regen_label")
        self.stats_group_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.energy_regen_label)
        self.energy_regen = QtWidgets.QSpinBox(self.widget)
        self.energy_regen.setMinimum(1)
        self.energy_regen.setMaximum(1000000)
        self.energy_regen.setSingleStep(10)
        self.energy_regen.setObjectName("energy_regen")
        self.stats_group_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.energy_regen)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.stats_group_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.line_2)
        self.hunger_label = QtWidgets.QLabel(self.widget)
        self.hunger_label.setObjectName("hunger_label")
        self.stats_group_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.hunger_label)
        self.hunger = QtWidgets.QSlider(self.widget)
        self.hunger.setMinimum(1)
        self.hunger.setOrientation(QtCore.Qt.Horizontal)
        self.hunger.setObjectName("hunger")
        self.stats_group_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.hunger)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.stats_group_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.line_3)
        self.warmth_label = QtWidgets.QLabel(self.widget)
        self.warmth_label.setObjectName("warmth_label")
        self.stats_group_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.warmth_label)
        self.warmth = QtWidgets.QSlider(self.widget)
        self.warmth.setMinimum(1)
        self.warmth.setOrientation(QtCore.Qt.Horizontal)
        self.warmth.setObjectName("warmth")
        self.stats_group_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.warmth)
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.stats_group_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.line_4)
        self.breath_label = QtWidgets.QLabel(self.widget)
        self.breath_label.setObjectName("breath_label")
        self.stats_group_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.breath_label)
        self.breath = QtWidgets.QSlider(self.widget)
        self.breath.setMinimum(1)
        self.breath.setOrientation(QtCore.Qt.Horizontal)
        self.breath.setObjectName("breath")
        self.stats_group_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.breath)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 10, 441, 521))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget1 = QtWidgets.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 421, 171))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pixels_label = QtWidgets.QLabel(self.widget1)
        self.pixels_label.setObjectName("pixels_label")
        self.gridLayout.addWidget(self.pixels_label, 0, 0, 1, 1)
        self.pixels = QtWidgets.QSpinBox(self.widget1)
        self.pixels.setMaximum(9999999)
        self.pixels.setSingleStep(100)
        self.pixels.setObjectName("pixels")
        self.gridLayout.addWidget(self.pixels, 0, 1, 1, 1)
        self.head_label = QtWidgets.QLabel(self.widget1)
        self.head_label.setObjectName("head_label")
        self.gridLayout.addWidget(self.head_label, 0, 2, 1, 1)
        self.head = QtWidgets.QLineEdit(self.widget1)
        self.head.setObjectName("head")
        self.gridLayout.addWidget(self.head, 0, 3, 1, 1)
        self.head_glamor = QtWidgets.QLineEdit(self.widget1)
        self.head_glamor.setObjectName("head_glamor")
        self.gridLayout.addWidget(self.head_glamor, 1, 3, 1, 1)
        self.chest_label = QtWidgets.QLabel(self.widget1)
        self.chest_label.setObjectName("chest_label")
        self.gridLayout.addWidget(self.chest_label, 2, 2, 1, 1)
        self.chest = QtWidgets.QLineEdit(self.widget1)
        self.chest.setObjectName("chest")
        self.gridLayout.addWidget(self.chest, 2, 3, 1, 1)
        self.chest_glamor = QtWidgets.QLineEdit(self.widget1)
        self.chest_glamor.setObjectName("chest_glamor")
        self.gridLayout.addWidget(self.chest_glamor, 3, 3, 1, 1)
        self.backpack_label = QtWidgets.QLabel(self.widget1)
        self.backpack_label.setObjectName("backpack_label")
        self.gridLayout.addWidget(self.backpack_label, 4, 0, 1, 1)
        self.backpack = QtWidgets.QLineEdit(self.widget1)
        self.backpack.setObjectName("backpack")
        self.gridLayout.addWidget(self.backpack, 4, 1, 1, 1)
        self.legs_label = QtWidgets.QLabel(self.widget1)
        self.legs_label.setObjectName("legs_label")
        self.gridLayout.addWidget(self.legs_label, 4, 2, 1, 1)
        self.legs = QtWidgets.QLineEdit(self.widget1)
        self.legs.setObjectName("legs")
        self.gridLayout.addWidget(self.legs, 4, 3, 1, 1)
        self.backpack_glamor = QtWidgets.QLineEdit(self.widget1)
        self.backpack_glamor.setObjectName("backpack_glamor")
        self.gridLayout.addWidget(self.backpack_glamor, 5, 1, 1, 1)
        self.legs_glamor = QtWidgets.QLineEdit(self.widget1)
        self.legs_glamor.setObjectName("legs_glamor")
        self.gridLayout.addWidget(self.legs_glamor, 5, 3, 1, 1)
        self.left_hand_label = QtWidgets.QLabel(self.widget1)
        self.left_hand_label.setObjectName("left_hand_label")
        self.gridLayout.addWidget(self.left_hand_label, 1, 0, 1, 1)
        self.right_hand_label = QtWidgets.QLabel(self.widget1)
        self.right_hand_label.setObjectName("right_hand_label")
        self.gridLayout.addWidget(self.right_hand_label, 2, 0, 1, 1)
        self.left_hand = QtWidgets.QLineEdit(self.widget1)
        self.left_hand.setObjectName("left_hand")
        self.gridLayout.addWidget(self.left_hand, 1, 1, 1, 1)
        self.right_hand = QtWidgets.QLineEdit(self.widget1)
        self.right_hand.setObjectName("right_hand")
        self.gridLayout.addWidget(self.right_hand, 2, 1, 1, 1)
        self.inv_tabs = QtWidgets.QTabWidget(self.groupBox_2)
        self.inv_tabs.setGeometry(QtCore.QRect(10, 200, 421, 311))
        self.inv_tabs.setObjectName("inv_tabs")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.action_bar = QtWidgets.QTableWidget(self.tab_5)
        self.action_bar.setGeometry(QtCore.QRect(0, 0, 417, 281))
        self.action_bar.setObjectName("action_bar")
        self.action_bar.setColumnCount(2)
        self.action_bar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.action_bar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.action_bar.setHorizontalHeaderItem(1, item)
        self.action_bar.horizontalHeader().setDefaultSectionSize(50)
        self.action_bar.horizontalHeader().setMinimumSectionSize(50)
        self.action_bar.horizontalHeader().setStretchLastSection(True)
        self.action_bar.verticalHeader().setVisible(False)
        self.inv_tabs.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.main_bag = QtWidgets.QTableWidget(self.tab_2)
        self.main_bag.setGeometry(QtCore.QRect(0, 0, 417, 281))
        self.main_bag.setAlternatingRowColors(True)
        self.main_bag.setCornerButtonEnabled(False)
        self.main_bag.setColumnCount(2)
        self.main_bag.setObjectName("main_bag")
        self.main_bag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.main_bag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_bag.setHorizontalHeaderItem(1, item)
        self.main_bag.horizontalHeader().setDefaultSectionSize(50)
        self.main_bag.horizontalHeader().setMinimumSectionSize(10)
        self.main_bag.horizontalHeader().setStretchLastSection(True)
        self.main_bag.verticalHeader().setVisible(False)
        self.inv_tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tile_bag = QtWidgets.QTableWidget(self.tab_3)
        self.tile_bag.setGeometry(QtCore.QRect(0, 0, 417, 281))
        self.tile_bag.setObjectName("tile_bag")
        self.tile_bag.setColumnCount(2)
        self.tile_bag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tile_bag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tile_bag.setHorizontalHeaderItem(1, item)
        self.tile_bag.horizontalHeader().setDefaultSectionSize(50)
        self.tile_bag.horizontalHeader().setMinimumSectionSize(50)
        self.tile_bag.horizontalHeader().setStretchLastSection(True)
        self.tile_bag.verticalHeader().setVisible(False)
        self.inv_tabs.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.equip_bag = QtWidgets.QTableWidget(self.tab)
        self.equip_bag.setGeometry(QtCore.QRect(0, 0, 417, 281))
        self.equip_bag.setAlternatingRowColors(True)
        self.equip_bag.setCornerButtonEnabled(False)
        self.equip_bag.setColumnCount(2)
        self.equip_bag.setObjectName("equip_bag")
        self.equip_bag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.equip_bag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.equip_bag.setHorizontalHeaderItem(1, item)
        self.equip_bag.horizontalHeader().setDefaultSectionSize(50)
        self.equip_bag.horizontalHeader().setMinimumSectionSize(10)
        self.equip_bag.horizontalHeader().setStretchLastSection(True)
        self.equip_bag.verticalHeader().setVisible(False)
        self.inv_tabs.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.wield_bag = QtWidgets.QTableWidget(self.tab_4)
        self.wield_bag.setGeometry(QtCore.QRect(0, 0, 417, 281))
        self.wield_bag.setAlternatingRowColors(True)
        self.wield_bag.setCornerButtonEnabled(False)
        self.wield_bag.setColumnCount(2)
        self.wield_bag.setObjectName("wield_bag")
        self.wield_bag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.wield_bag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wield_bag.setHorizontalHeaderItem(1, item)
        self.wield_bag.horizontalHeader().setDefaultSectionSize(50)
        self.wield_bag.horizontalHeader().setMinimumSectionSize(10)
        self.wield_bag.horizontalHeader().setStretchLastSection(True)
        self.wield_bag.verticalHeader().setVisible(False)
        self.inv_tabs.addTab(self.tab_4, "")
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 281, 131))
        self.widget2.setObjectName("widget2")
        self.formLayout = QtWidgets.QFormLayout(self.widget2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.name = QtWidgets.QLineEdit(self.widget2)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.race_label = QtWidgets.QLabel(self.widget2)
        self.race_label.setObjectName("race_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.race_label)
        self.gender_label = QtWidgets.QLabel(self.widget2)
        self.gender_label.setObjectName("gender_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gender_label)
        self.widget3 = QtWidgets.QWidget(self.widget2)
        self.widget3.setMinimumSize(QtCore.QSize(0, 20))
        self.widget3.setObjectName("widget3")
        self.male = QtWidgets.QRadioButton(self.widget3)
        self.male.setGeometry(QtCore.QRect(0, 0, 57, 19))
        self.male.setObjectName("male")
        self.female = QtWidgets.QRadioButton(self.widget3)
        self.female.setGeometry(QtCore.QRect(60, 0, 72, 19))
        self.female.setObjectName("female")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.widget3)
        self.desc_label = QtWidgets.QLabel(self.widget2)
        self.desc_label.setObjectName("desc_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.desc_label)
        self.description = QtWidgets.QTextEdit(self.widget2)
        self.description.setObjectName("description")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.description)
        self.name_label = QtWidgets.QLabel(self.widget2)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.race = QtWidgets.QLineEdit(self.widget2)
        self.race.setObjectName("race")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.race)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionManage_Blueprints = QtWidgets.QAction(MainWindow)
        self.actionManage_Blueprints.setObjectName("actionManage_Blueprints")
        self.actionManage_Techs = QtWidgets.QAction(MainWindow)
        self.actionManage_Techs.setObjectName("actionManage_Techs")
        self.actionMake_Backups = QtWidgets.QAction(MainWindow)
        self.actionMake_Backups.setCheckable(True)
        self.actionMake_Backups.setChecked(True)
        self.actionMake_Backups.setObjectName("actionMake_Backups")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionMake_Backups)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionManage_Blueprints)
        self.menuTools.addAction(self.actionManage_Techs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.inv_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "starcheat"))
        self.stats_group.setTitle(_translate("MainWindow", "Stats"))
        self.health_label.setText(_translate("MainWindow", "Health"))
        self.max_health_label.setText(_translate("MainWindow", "Max"))
        self.invulnerable.setText(_translate("MainWindow", "Invulnerable"))
        self.godmode.setText(_translate("MainWindow", "God Mode"))
        self.energy_label.setText(_translate("MainWindow", "Energy"))
        self.max_energy_label.setText(_translate("MainWindow", "Max"))
        self.energy_regen_label.setText(_translate("MainWindow", "Regen"))
        self.hunger_label.setText(_translate("MainWindow", "Hunger"))
        self.warmth_label.setText(_translate("MainWindow", "Warmth"))
        self.breath_label.setText(_translate("MainWindow", "Breath"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Inventory"))
        self.pixels_label.setText(_translate("MainWindow", "Pixels"))
        self.head_label.setText(_translate("MainWindow", "Head"))
        self.chest_label.setText(_translate("MainWindow", "Chest"))
        self.backpack_label.setText(_translate("MainWindow", "Backpack"))
        self.legs_label.setText(_translate("MainWindow", "Legs"))
        self.left_hand_label.setText(_translate("MainWindow", "Left Hand"))
        self.right_hand_label.setText(_translate("MainWindow", "Right Hand"))
        item = self.action_bar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Count"))
        item = self.action_bar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        self.inv_tabs.setTabText(self.inv_tabs.indexOf(self.tab_5), _translate("MainWindow", "Action Bar"))
        item = self.main_bag.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Count"))
        item = self.main_bag.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        self.inv_tabs.setTabText(self.inv_tabs.indexOf(self.tab_2), _translate("MainWindow", "Main Bag"))
        item = self.tile_bag.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Count"))
        item = self.tile_bag.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        self.inv_tabs.setTabText(self.inv_tabs.indexOf(self.tab_3), _translate("MainWindow", "Tile Bag"))
        item = self.equip_bag.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Count"))
        item = self.equip_bag.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        self.inv_tabs.setTabText(self.inv_tabs.indexOf(self.tab), _translate("MainWindow", "Equipment"))
        item = self.wield_bag.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Count"))
        item = self.wield_bag.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        self.inv_tabs.setTabText(self.inv_tabs.indexOf(self.tab_4), _translate("MainWindow", "Wielded"))
        self.race_label.setText(_translate("MainWindow", "Race"))
        self.gender_label.setText(_translate("MainWindow", "Gender"))
        self.male.setText(_translate("MainWindow", "Male"))
        self.female.setText(_translate("MainWindow", "Female"))
        self.desc_label.setText(_translate("MainWindow", "Description"))
        self.name_label.setText(_translate("MainWindow", "Name"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open a player save file"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save player changes"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Quit program"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionManage_Blueprints.setText(_translate("MainWindow", "Manage Blueprints"))
        self.actionManage_Techs.setText(_translate("MainWindow", "Manage Techs"))
        self.actionMake_Backups.setText(_translate("MainWindow", "Make Backups"))

